  version: '3.8'

  services:
    postgres:
      image: postgres:15
      container_name: see-more-postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: see_more_db
      ports:
        - '5432:5432'
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./see-more-nest/schemas:/docker-entrypoint-initdb.d
      networks:
        - see-more-network

    backend:
      build:
        context: ./see-more-nest
        dockerfile: Dockerfile
      container_name: see-more-backend
      restart: always
      environment:
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_NAME: see_more_db
        PORT: 3000
      ports:
        - '3000:3000'
      depends_on:
        - postgres
      networks:
        - see-more-network

    frontend:
      build:
        context: ./see-more-angular
        dockerfile: Dockerfile
      container_name: see-more-frontend
      restart: always
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - certbot_conf:/etc/letsencrypt
        - certbot_www:/var/www/certbot
      depends_on:
        - backend
      networks:
        - see-more-network
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
      image: certbot/certbot
      container_name: see-more-certbot
      restart: unless-stopped
      volumes:
        - certbot_conf:/etc/letsencrypt
        - certbot_www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  volumes:
    postgres_data:
    certbot_conf:
    certbot_www:

  networks:
    see-more-network:
      driver: bridge